### ISSUE TITLE
Steer inside shape 

### ISSUE THREAD

**Issue by DQvsRA** [ricardojmendez/UnitySteerExamples#3]
Is it possible to limit wanderer movement inside imported mesh like a big fish?

**Comment by ricardojmendez** [comment]
I'm not sure if you mean having the movement constrained to the mesh volume, or having it move on top of a mesh volume. Either case would be possible - the first is closer to SteerForTether, whereas the other would depend on your implementation (eg., a Super Mario Galaxy-like movement vs. a normal gravity biped).

**Comment by DQvsRA** [comment]
I mean "movement constrained to the mesh volume". Thank you, i will try it.
